// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbkQSYPURBEQHOt4TFmxZAFGjvnjr1xHU',
    appId: '1:282963756292:web:ff3a01f004d5b8a25c3c51',
    messagingSenderId: '282963756292',
    projectId: 'edunex-51df4',
    authDomain: 'edunex-51df4.firebaseapp.com',
    storageBucket: 'edunex-51df4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTH7ci__IyDt3rZt7PfHqWa_VxDl1tLLA',
    appId: '1:282963756292:android:47ac82434f538ad15c3c51',
    messagingSenderId: '282963756292',
    projectId: 'edunex-51df4',
    storageBucket: 'edunex-51df4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwilxNk1D-mCUa6OjCHxShAIcsynVDNw',
    appId: '1:282963756292:ios:4d4b48098267cb545c3c51',
    messagingSenderId: '282963756292',
    projectId: 'edunex-51df4',
    storageBucket: 'edunex-51df4.firebasestorage.app',
    iosBundleId: 'com.example.edunexApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwilxNk1D-mCUa6OjCHxShAIcsynVDNw',
    appId: '1:282963756292:ios:4d4b48098267cb545c3c51',
    messagingSenderId: '282963756292',
    projectId: 'edunex-51df4',
    storageBucket: 'edunex-51df4.firebasestorage.app',
    iosBundleId: 'com.example.edunexApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbkQSYPURBEQHOt4TFmxZAFGjvnjr1xHU',
    appId: '1:282963756292:web:9c493cbcef92b63f5c3c51',
    messagingSenderId: '282963756292',
    projectId: 'edunex-51df4',
    authDomain: 'edunex-51df4.firebaseapp.com',
    storageBucket: 'edunex-51df4.firebasestorage.app',
  );
}
